Internet-Programming/Django/pythonWeb/mysite/elections/urls.py
from django.conf.urls import url
from . import views

app_name = 'elections'
urlpatterns = [
    url(r'^$', views.index, name = 'home'),
    url(r'^areas/(?P<area>[가-힣]+)/$', views.areas),
    url(r'^areas/(?P<area>[가-힣]+)/results$', views.results),
    url(r'^polls/(?P<poll_id>\d+)/$', views.polls),
    url(r'^candidates/(?P<name>[가-힣]+)/$', views.candidates)
]

Internet-Programming/Django/pythonWeb/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^', include('elections.urls')),
    path('admin/', admin.site.urls),
]

Internet-Programming/Django/pythonWeb/mysite/elections/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    name = models.CharField(max_length=10)
    introduction = models.TextField()
    area = models.CharField(max_length=15)
    party_number = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Poll(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    area = models.CharField(max_length=15)

class Choice(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    votes = models.IntegerField(default = 0)

Internet-Programming/Django/pythonWeb/mysite/elections/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect,HttpResponseNotFound, Http404
from .models import Candidate, Poll, Choice
import datetime
from django.db.models import Sum

def index(request):
    candidates = Candidate.objects.all()
    context = {'candidates':candidates}
    return render(request, 'elections/index.html', context)

def candidates(request, name):
    candidate = get_object_or_404(Candidate, name=name)
    """
    try:
        candidate = Candidate.objects.get(name = name)
    except:
        #return HttpResponseNotFound("없는 페이지입니다.")
        raise Http404
    """
    return HttpResponse(candidate.name)

def areas(request, area):
    today = datetime.datetime.now()
    try:
        poll = Poll.objects.get(area=area, start_date__lte=today, end_date__gte=today)
        candidate = Candidate.objects.filter(area = area)
    except:
        poll = None
        candidate = None
    context = {'candidates': candidate, 'area': area, 'poll': poll}
    return render(request, 'elections/area.html', context)

def polls(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    selection = request.POST['choice']
    try:
        choice = Choice.objects.get(poll_id=poll_id, candidate_id=selection)
        choice.votes += 1
        choice.save()
    except:
        choice = Choice(poll_id=poll_id, candidate_id=selection, votes=1)
        choice.save()
    return HttpResponseRedirect("/areas/{}/results".format(poll.area))

def results(request, area):
    candidates = Candidate.objects.filter(area=area)
    polls = Poll.objects.filter(area=area)
    poll_results = []
    for poll in polls:
        result = {}
        result['start_date'] = poll.start_date
        result['end_date'] = poll.end_date
        total_votes = Choice.objects.filter(poll_id=poll.id).aggregate(Sum('votes'))
        #print("#########", total_votes)
        result['total_votes'] = total_votes['votes__sum']

        rates = []
        for candidate in candidates:
            try:
                choice = Choice.objects.get(poll_id = poll.id, candidate_id = candidate.id)
                rates.append(round(choice.votes * 100 / result['total_votes'],1))
            except:
                rates.append(0)
        result['rates'] = rates
        poll_results.append(result)

    context = {'candidates': candidates, 'area': area, 'poll_results' : poll_results}
    return render(request, 'elections/result.html', context)

Internet-Programming/Django/pythonWeb/mysite/elections/templates/elections/area.html
{% extends "elections/layout.html"%}
{%block title %}
{{area}}
{% endblock %}
{% block content %}
<div class="container">
<h1>{{area}}</h1>
<br>
    {% if poll %}
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>기호</B></td>
            <td><B>지지하기</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
        <tr>
            <td> {{candidate.name}} </td>
            <td> {{candidate.introduction}} </td>
            <td> 기호{{candidate.party_number}}번 </td>
            <td>
                <form action = "/polls/{{poll.id}}/" method="post">
                 {% csrf_token %}
                    <button name="choice" value="{{candidate.id}}">선택</button>
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    여론조사가 없습니다.
    {% endif %}
</div>
{% endblock %}

Internet-Programming/Django/pythonWeb/mysite/elections/templates/elections/index.html
{% extends "elections/layout.html"%}
{%block title %}
선거 후보
{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>소개</B></td>
            <td><B>출마지역</B></td>
            <td><B>기호</B></td>
        </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
        <tr>
            <td>{{candidate.name}}</td>
            <td>{{candidate.introduction}}</td>
            <td> <a href = "areas/{{candidate.area}}/">
            {{candidate.area}}</a></td>
            <td>기호{{candidate.party_number}}번</td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
{% endblock %}

Internet-Programming/Django/pythonWeb/mysite/elections/templates/elections/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel ="shortcut icon" type = "image/icon" href="{% static 'elections/favicon.ico' %}" />
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'elections:home' %}">미국 대선</a>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

Internet-Programming/Django/pythonWeb/mysite/elections/templates/elections/result.html
{% extends "elections/layout.html"%}
{%block title %}
{{area}} 여론 조사 결과
{% endblock %}
{% block content %}
<div class="container">
<h1>{{area}}</h1>
<br>
<table class="table table-striped">
    <thead>
    <tr>
        <td><B>기간</B></td>
         {% for candidate in candidates %}
        <td><B>{{candidate.name}}</B></td>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for result in poll_results %}
    <tr>
        <td> {{result.start_date.year}}/{{result.start_date.month}}/{{result.start_date.day}}~{{result.end_date.year}}/{{result.end_date.month}}/{{result.end_date.day}} </td>
        {% for rate in result.rates %}
        <td> {{rate}}% </td>
        {% endfor %}
    </tr>
    {% endfor %}
    <tbody>
</table>
</div>
{% endblock %}